### ISSUE TITLE
How to import USDZ file

### ISSUE THREAD

**Issue by eilidan** [piemonte/obj2usdz#1]
Thanks for your work. I have download your project and have already installed Xcode. But I do not know how to use Xcode. I 'd like to ask you how to export usdz files with Xcode.Thanks a lot.

**Comment by piemonte** [comment]
hey @eilidan thanks for the interest.

it's best to learn from Apple's documentation and post questions to stackoverflow. as quick run of your question, import your model with ModelIO, then use the code from this project to export that file to USDZ as shown in the readme.

best of luck.
